"""empty message

Revision ID: 0f35fda8008a
Revises: ed92ee52907c
Create Date: 2023-07-15 13:14:34.193729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f35fda8008a'
down_revision = 'ed92ee52907c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bookauthor_id', sa.BigInteger(), nullable=False))
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('book_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.drop_index('books')

    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booklisting_id', sa.BigInteger(), nullable=False))
        batch_op.alter_column('book_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('listing_id',
               existing_type=mysql.BIGINT(),
               nullable=True)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('isbn_code',
               existing_type=mysql.BIGINT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('subject_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('publisher_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('grade_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['isbn_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('grade_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('publisher_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('subject_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('isbn_code',
               existing_type=mysql.BIGINT(),
               nullable=False)

    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.alter_column('listing_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('book_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.drop_column('booklisting_id')

    with op.batch_alter_table('book_authors', schema=None) as batch_op:
        batch_op.create_index('books', ['book_id'], unique=False)
        batch_op.alter_column('book_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('author_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('bookauthor_id')

    # ### end Alembic commands ###
