"""empty message

Revision ID: 20988c29b89d
Revises: 
Create Date: 2023-07-08 17:53:08.155095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20988c29b89d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listed_books')
    op.drop_table('grades')
    op.drop_table('authors')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index('ix_subjects_subject_name')

    op.drop_table('subjects')
    op.drop_table('books')
    with op.batch_alter_table('book_images', schema=None) as batch_op:
        batch_op.drop_index('image_path')

    op.drop_table('book_images')
    op.drop_table('publishers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('email_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_index('first_name_2')
        batch_op.drop_index('username_2')
        batch_op.create_index(batch_op.f('ix_users_email_address'), ['email_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)
        batch_op.drop_column('signup_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signup_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_last_name'))
        batch_op.drop_index(batch_op.f('ix_users_first_name'))
        batch_op.drop_index(batch_op.f('ix_users_email_address'))
        batch_op.create_index('username_2', ['username', 'email_address'], unique=False)
        batch_op.create_index('first_name_2', ['first_name', 'last_name', 'username', 'email_address', 'phone_number'], unique=False)
        batch_op.alter_column('is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('phone_number',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email_address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('publishers',
    sa.Column('publisher_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('shortname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('longname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ISBN', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('date_added', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('publisher_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('book_images',
    sa.Column('image_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listing_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image_size', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listed_books.listing_id'], name='book_images_ibfk_1'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], name='book_images_ibfk_2'),
    sa.PrimaryKeyConstraint('image_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('book_images', schema=None) as batch_op:
        batch_op.create_index('image_path', ['image_path'], unique=False)

    op.create_table('books',
    sa.Column('book_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('isbn_code', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('subject_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('publisher_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('grade_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], name='books_ibfk_1'),
    sa.PrimaryKeyConstraint('book_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('subjects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subject_name', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index('ix_subjects_subject_name', ['subject_name'], unique=False)

    op.create_table('authors',
    sa.Column('author_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('author_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('book_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.book_id'], name='FK_AuthorBook'),
    sa.PrimaryKeyConstraint('author_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('grades',
    sa.Column('grade_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('grade_num', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grade_name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('grade_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('listed_books',
    sa.Column('listing_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('listed_by', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('book_title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('options', mysql.ENUM('SELL', 'EXCHANGE', 'BOTH'), nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('book_condition', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('publisher_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('grade_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('listing_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.grade_id'], name='listed_books_ibfk_3'),
    sa.ForeignKeyConstraint(['listed_by'], ['users.user_id'], name='listed_books_ibfk_1'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.publisher_id'], name='listed_books_ibfk_2'),
    sa.PrimaryKeyConstraint('listing_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
