"""empty message

Revision ID: 4153b3470acb
Revises: 7acb302c9860
Create Date: 2023-07-16 00:56:20.522127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4153b3470acb'
down_revision = '7acb302c9860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('grade_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('publisher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['author_id'])
        batch_op.create_foreign_key(None, 'grades', ['grade_id'], ['grade_id'])
        batch_op.create_foreign_key(None, 'publishers', ['publisher_id'], ['publisher_id'])
        batch_op.create_foreign_key(None, 'books', ['book_name'], ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')
        batch_op.drop_column('publisher_id')
        batch_op.drop_column('grade_id')
        batch_op.drop_column('book_name')

    # ### end Alembic commands ###
