"""empty message

Revision ID: 45f0d33c1376
Revises: eae5c8062638
Create Date: 2023-07-16 15:57:31.754949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f0d33c1376'
down_revision = 'eae5c8062638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listed_by', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.drop_column('listed_by')

    # ### end Alembic commands ###
