"""empty message

Revision ID: 477034bc3345
Revises: 7c58f3995678
Create Date: 2023-07-08 22:34:29.934689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477034bc3345'
down_revision = '7c58f3995678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['added_by'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
