"""empty message

Revision ID: 56774ff34055
Revises: ca1deee956bb
Create Date: 2023-07-16 15:49:14.562751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56774ff34055'
down_revision = 'ca1deee956bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'publishers', ['publisher_id'], ['publisher_id'])
        batch_op.create_foreign_key(None, 'books', ['book_name'], ['title'])
        batch_op.create_foreign_key(None, 'grades', ['grade_id'], ['grade_id'])
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['author_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
