"""empty message

Revision ID: ad8bc21f5ae1
Revises: 69cf6062f3ad
Create Date: 2023-07-16 18:24:17.813757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad8bc21f5ae1'
down_revision = '69cf6062f3ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.drop_column('book_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_title', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
