"""empty message

Revision ID: b471e205ee61
Revises: 
Create Date: 2022-03-31 04:08:17.888789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b471e205ee61'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_subject_name'), 'subjects', ['subject_name'], unique=True)
    op.drop_table('books')
    op.drop_table('listed_books')
    op.drop_table('users')
    op.drop_table('publishers')
    op.drop_table('Grades')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grades',
    sa.Column('grade_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('grade_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('grade_name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('grade_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('publishers',
    sa.Column('publisher_id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('shortname', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('longname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ISBN', mysql.BIGINT(display_width=13), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('date_added', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('publisher_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email_address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('signup_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('listed_books',
    sa.Column('listing_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('listed_by', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('book_title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('options', mysql.ENUM('sell', 'exchange', 'both'), nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=20), autoincrement=False, nullable=True),
    sa.Column('book_condition', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('listing_date', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('publisher_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('grade_name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('listing_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('books',
    sa.Column('book_id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('isbn_code', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('publisher_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('grade_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('book_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_subjects_subject_name'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
