"""empty message

Revision ID: ee8fde69b5a4
Revises: 1d83cc0207ff
Create Date: 2023-07-08 22:19:14.351348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ee8fde69b5a4'
down_revision = '1d83cc0207ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.alter_column('added_by',
               existing_type=mysql.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('date_added',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.create_unique_constraint(None, ['ISBN_code'])
        batch_op.create_foreign_key(None, 'users', ['added_by'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publishers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('date_added',
               existing_type=sa.Integer(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('added_by',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
